name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Create application.properties with secret URI
      - name: Set up application.properties
        run: |
          echo "spring.data.mongodb.uri=${{ secrets.MONGODB_URI }}" > src/main/resources/application.properties

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test

      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:

          image: kadklk/uniconnect_backend
          tags: latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKaER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
